#Deciding whether to enable the cluster The default value is false.
clusterModel = false

[address]
port = 1883
host = "127.0.0.1"



[unAckMessage]
# unack msg reSend time interval
reSendMs = 5_000

